stages:
- Remote-Check-Out
- Remote-Code-Scanning
- Code Check-In

Remote-Check-Out:
  stage: Remote-Check-Out
  script:
    - pwd

Remote-Code-Scanning:
  stage: Remote-Code-Scanning
  script:
    - pwd

Code Check-In:
  stage: Code Check-In
  script:
    - pwd
