include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/License-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
variables:
  SECURE_ANALYZERS_PREFIX: "harbor.rke.pandora.com/gitlab"
  SCAN_KUBERNETES_MANIFESTS: "true"

stages:
- Remote-Check-Out
- Project-Build
- test
- XCA-Testing
- Container-Image-Scanning
- Check-Quality-Gate
- Push-Image

Remote-Check-Out:
  stage: Remote-Check-Out
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop

# Sast-Scan:
#   stage: Sast-Scan
#   image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep
#   script:
#     - echo "sast scan"
#     # - semgrep --config=p/security-audit --json Build_Pipeline
#   artifacts:
#     reports:
#       sast: gl-sast-report.json

Project-Build:
  stage: Project-Build
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop


XCA-Testing:
  stage: XCA-Testing
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop

Container-Image-Scanning:
  stage: Container-Image-Scanning
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop

Check-Quality-Gate:
  stage: Check-Quality-Gate
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop

Push-Image:
  stage: Push-Image
  image: docker:19.03.12
  script:
    - pwd
  only:
    - develop