name: Java Project - Github 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      # run: mvn -B package --file pom.xml
      run: |
        mvn -N io.takari:maven:wrapper
        ./mvnw clean install
        cd spring-petclinic-server
        mvn clean package docker:build -X
